### ISSUE TITLE
EnvFile 3.4.1 crash

### ISSUE THREAD

**Issue by RonCWing** [Ashald/EnvFile#215]
Relevant Stack:

java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
	at net.ashald.envfile.providers.yaml.YamlEnvFileParser.parse(YamlEnvFileParser.java:15)
	at net.ashald.envfile.providers.SingleFileEnvVarsProvider.getEnvVars(SingleFileEnvVarsProvider.java:41)
	at net.ashald.envfile.platform.EnvFileEnvironmentVariables.render(EnvFileEnvironmentVariables.java:67)
	at net.ashald.envfile.products.goland.GolandRunConfigurationExtension.patchCommandLine(GolandRunConfigurationExtension.java:37)
	at com.goide.execution.extension.GoRunConfigurationExtensionsManager.lambda$patchCommandLine$1(GoRunConfigurationExtensionsManager.java:57)
	at com.intellij.execution.configuration.RunConfigurationExtensionsManager.processEnabledExtensions(RunConfigurationExtensionsManager.kt:228)
	at com.goide.execution.extension.GoRunConfigurationExtensionsManager.patchCommandLine(GoRunConfigurationExtensionsManager.java:55)
	at com.goide.execution.GoRunningState.lambda$patchCommandLine$5(GoRunningState.java:350)
	at com.goide.util.GoLocalEnvironmentRequest$GoLocalRemoteEnvironment.createGeneralCommandLine(GoLocalEnvironmentRequest.java:143)
	at com.intellij.execution.target.local.LocalTargetEnvironment.createProcess(LocalTargetEnvironment.java:129)
	at com.goide.util.GoExecutor$3.getProcessHandler(GoExecutor.java:579)
	at com.goide.util.GoExecutor$3.run(GoExecutor.java:531)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by cmmoran** [comment]
Can you paste a snippet of what your yaml looks like?

**Comment by RonCWing** [comment]
Hi, I'm attaching here the yaml (which all characters masked):

# xxx-xxx-xxx-xxx.sh generated vars
WWWW_WWWW_WWWW_WWWW_WWWW_WWWW_WWWW_WWWW=xxxxx]x'xxxx^xxxxx
WWWW_WWWW_WWWW_WWWW_WWWW_WWWW_WWWW=1234
WWWW_WWWW_WWWW_WWWW_WWWW_WWWW=xxxxx.xxxxx.xxxx-xxxx-xxx.xxxx.xxxxx.xxxx
WWWW_WWWW_WWWW_WWWW_WWWW=xxxx
WWWW_WWWW_WWWW_WWWW=xxxx
WWWW_WWWW_WWWW=xxxx
WWWW_WWWW=xxx:xxx:xxxx:xxx-xxxxx-9:xxxxxxx:xxxx:xxx-xxx
WWWW_=xxxxx
ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ=xxxx
ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ=xxxx
ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ=xxx-xxxx-9
ZZZ_ZZZ_ZZZ_ZZZ_ZZZ_ZZZ=xxx:xxx:xxxxxx:xxx-xxxx-9:xxxxx:xxxx:xxxx-xxxxxx-xxxxx-xxxxx-xxxx
ZZZ_ZZZ_ZZZ_ZZZ_ZZZ=true
ZZZ_ZZZ_ZZZ_ZZZ=xxxx
ZZZ_ZZZ_ZZZ=true
ZZZ_ZZZ=xxx:xxx:xxxxxx:xx-xxx-9:xxxxxx:xxxx:xxx-xxx-xxx-xxxx
ZZZ=https://xxxxxxx.xxxxx.xxxxx/
YYY=https://xxxx-xxxxx.xxxx.xxxx.xxxxx/
YYY_YYY=xxxxxx
YYY_YYY_YYY=xxxxxx
YYY_YYY_YYY_YYY=dev-xxxx.xxx.xxx.xxxxx
YYY_YYY_YYY_YYY_YYY=xxxxxxx
YYY_YYY_YYY_YYY_YYY_YYY=xxxxxxx
YYY_YYY_YYY_YYY_YYY_YYY_YYY=xxxxxxx
YYY_YYY_YYY_YYY_YYY_YYY_YYY_YYY=xxxxxxxx
YYY_YYY_YYY_YYY_YYY_YYY_YYY_YYY_YYY=xxxxxxxxx
YYY_YYY_YYY_YYY_YYY_YYY_YYY_YYY_YYY_YYY=xxxxxxxxx
XXX=xxxxxx-xxxxxx
XXX_XXX=xxxxxxxxx
XXX_XXX_XXX=xxx:aws:xxxxxxxxxx:xxxx-xxxx-9:xxxxxx:secret:xxxx-xxxx-xxxx-xxx-xxxx-xxx2131x
XXX_XXX_XXX_XXX=xxxx:aws:xxxxxxxxxx:xxxx-xxxx-9:xxxx:xxxxx:xxxx-xxxx-xxxx-xxxx-key-xxxxxx
XXX_XXX_XXX_XXX_XXX=xxxx:aws:xxxxxxxxxx:xxxx-xxxxx-9:1234:secret:xxxxx-xxxx-xxxx-xxxx-xxxx6xxx
XXX_XXX_XXX_XXX_XXX_XXX=xxxx:aws:xxxxxxxxxx:xxxx-xxxx-9:1234:secret:xxxxx-xxxx-xxxx-xxxx-xxxx-xxxx
XXX_XXX_XXX_XXX_XXX_XXX_XXX=xxxxx:xxxx:xxxxxxxxxx:xxxx-xxxx-9:1234:xxxx:xxxx-xxxx-xxxxx-xxxx-xxxxx-xxxx-xxxx-xxx7xxx
XXX_XXX_XXX_XXX_XXX_XXX_XXX_XXX=xxxxxxxx:xxxxx:xxxxxxxxxx:xxx-xxxxx-9:1234:xxxxx:xxxx-xxxx-xxxx-xxxxx-xxxx-xxxxx7

**Comment by RonCWing** [comment]
[envFileIssue.txt](https://github.com/ashald/EnvFile/files/11028514/envFileIssue.txt)

**Comment by cmmoran** [comment]
This is a duplicate of [#213](https://github.com/ashald/EnvFile/issues/213) and fixed in #211.

Take a look at that PR and see if that change fixes this issue for you.
