### ISSUE TITLE
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by refack** [Ashald/EnvFile#32]
```java
Malformed \uxxxx encoding.
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.util.Properties.loadConvert(Properties.java:574)
	at java.util.Properties.load0(Properties.java:391)
	at java.util.Properties.load(Properties.java:341)
	at net.ashald.envfile.parsers.DotEnvFileParser.readFile(DotEnvFileParser.java:26)
	at net.ashald.envfile.AbstractEnvFileParser.process(AbstractEnvFileParser.java:19)
	at net.ashald.envfile.platform.EnvFileEntry.process(EnvFileEntry.java:66)
	at net.ashald.envfile.platform.ui.EnvFileConfigurationEditor.patchEnvironmentVariables(EnvFileConfigurationEditor.java:113)
	at net.ashald.envfile.products.pycharm.PyCharmRunConfigurationExtension.patchCommandLine(PyCharmRunConfigurationExtension.java:53)
	at net.ashald.envfile.products.pycharm.PyCharmRunConfigurationExtension.patchCommandLine(PyCharmRunConfigurationExtension.java:16)
	at com.intellij.execution.configuration.RunConfigurationExtensionsManager.patchCommandLine(RunConfigurationExtensionsManager.java:160)
	at com.jetbrains.python.run.PythonCommandLineState.startProcess(PythonCommandLineState.java:216)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:144)
	at com.jetbrains.python.run.PythonScriptCommandLineState.execute(PythonScriptCommandLineState.java:112)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:138)
	at com.jetbrains.python.debugger.PyDebugRunner.createSession(PyDebugRunner.java:136)
	at com.jetbrains.python.debugger.PyDebugRunner.doExecute(PyDebugRunner.java:164)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.RunProfileStarter.executeAsync(RunProfileStarter.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:390)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:447)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:304)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:447)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:37)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:122)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:69)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:539)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Adding my file as ZIP incase it's an encoding / UTF-8 BOM issue
[14.10.25017.zip](https://github.com/Ashald/EnvFile/files/870359/14.10.25017.zip)

**Comment by ashald** [comment]
Thanks for report, will try to fix it next release!

**Comment by Varun200864** [comment]
What is workaround for now?
How can one load file which contains special characters?

**Comment by ashald** [comment]
Fixed, will be released soon.
