### ISSUE TITLE
[Bug] Plugin conflict with IDEA ScalaTest

### ISSUE THREAD

**Issue by aotd1** [Ashald/EnvFile#53]
If I create ScalaTest Run/Debug Configuration and enable EnvFile something went wrong. When I'm trying to run this configuration i've got error:
```
Error running 'IT-tests':
Unknown error
```

If I restart IDE - error disappears. If I change something in 'IT-tests' configuration - it appears again and Configuration Environment variables fills with .env file content (it didn't happen before as I remember)

**IDE**
IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 25, 2017

JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
 
**idea.log**
```log
2018-01-12 10:08:47,515 [ 316559]   INFO - s.CompilerReferenceServiceImpl - backward reference index reader is opened 
2018-01-12 10:08:47,653 [ 316697]   WARN - xecution.runners.ExecutionUtil - Execution error without description 
java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.clear(ImmutableMap.java:620)
	at net.ashald.envfile.platform.ui.EnvFileConfigurationEditor.patchEnvironmentVariables(EnvFileConfigurationEditor.java:122)
	at net.ashald.envfile.products.idea.IdeaRunConfigurationExtension.updateJavaParameters(IdeaRunConfigurationExtension.java:53)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration$$anon$2.$anonfun$createJavaParameters$8(AbstractTestRunConfiguration.scala:442)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration$$anon$2.$anonfun$createJavaParameters$8$adapted(AbstractTestRunConfiguration.scala:441)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at org.jetbrains.plugins.scala.testingSupport.test.AbstractTestRunConfiguration$$anon$2.createJavaParameters(AbstractTestRunConfiguration.scala:441)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:33)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:90)
	at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:75)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-01-12 10:08:48,245 [ 317289]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /Applications/IntelliJ IDEA.app/Contents/lib/jps-launcher.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/tools.jar:/Applications/IntelliJ IDEA.app/Contents/lib/optimizedFileManager.jar 
2018-01-12 10:08:48,306 [ 317350]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
2018-01-12 10:08:48,306 [ 317350]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: Defaulting to no-operation (NOP) logger implementation 
2018-01-12 10:08:48,306 [ 317350]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Enabled plugins**
Database Tools and SQL
Env File
Git Integration
Scala
YAML

**Comment by aotd1** [comment]
The same bug in IntelliJ IDEA CE

**Comment by ashald** [comment]
This is from `scala` plugin? Interesting, looks like they define env vars as an immutable map. I'll check if this can be fixed but cannot guarantee there will be a way around it.

**Comment by aotd1** [comment]
Yes, scala plugin only affected. May be it can be fixed in Scala plugin itself, not in EnvFile...
It looks like Scala plugin replaces env vars with immutable map only when I change something in "Edit Configuration..."
